### ISSUE TITLE
Sidebar from left

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/light-bootstrap-dashboard-pro#20]
Hi! Please follow the next steps:

1.First you must to go on html page and add to body tag the class `menu-on-left`.

2.Second go to `assets/sass/lbd/_responsive.scss` and add the following lines of code:

```css
@media (max-width: 991px){
     .menu-on-left{
         .sidebar,
         .off-canvas-sidebar{
              left: 0;
              right: auto;
              @include transform-translate-x(-260px);
         }
     }

     .nav-open .menu-on-left{
        .main-panel,
        .wrapper-full-page,
        .navbar-fixed > div{
             @include transform-translate-x(260px);
        }

        .sidebar,
        .off-canvas-sidebar{
             @include transform-translate-x(0px);
        }
    }
}
```
3.Compile your scss with [Koala](http://koala-app.com/) `assets/scss/light-bootstrap-dashboard.scss`.

4.Go to `assets/js/light-bootstrap-dashboard.js` and add the following code on line 69 and line 112:
```js
  line 69: if( $(window).width() <= 991 && $('body').hasClass('menu-on-left') ){
              $('.main-panel').css('position','fixed');
           }

  line 112: if( $(window).width() <= 991 && $('body').hasClass('menu-on-left') ){
               $('.main-panel').css('position','fixed');
            } else {
               $('.main-panel').css('position','');
            }
```
